name: Diff-JJoules Demo Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  diff-jjoules-demo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          path: v2
          clean: false
      - name: Build V2 with Maven
        run: mvn install -DskipTests dependency:build-classpath -Dmdep.outputFile=classpath
      - name: Clone V1
        run: git clone http://github.com/${{ github.repository }} -b ${{ github.base_ref }} ../v1
      - name: Build V1 with Maven
        run: mvn install -DskipTests dependency:build-classpath -Dmdep.outputFile=classpath -f ../v1/pom.xml
      - name: Diff-JJoules Demo
        run: mvn -f ../v1/pom.xml clean fr.davidson:diff-jjoules-maven:diff-jjoules -Dpath-dir-second-version=/home/benjamin/workspace/actions-runner/_work/diff-jjoules-demo/v2 -Dsuspect=false

  comment_pr:
    runs-on: self-hosted
    needs: diff-jjoules-demo
    if: always()
    steps:
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: template.md
        
  cleanup:
    runs-on: self-hosted
    needs: comment_pr
    if: always()
    steps:
      - name: Cleanup
        run: rm -rf ../v1
