name: Diff-JJoules Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Build V1 with Maven
        run: mvn install -DskipTests
      - uses: actions/checkout@v1
      - name: Build and Mutate V2 with Maven
        run: mvn install -DskipTests dependency:build-classpath -Dmdep.outputFile=classpath fr.davidson:untare-jjoules:mutate -Dmethod-names-per-full-qualified-names=methodNames.csv
