name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        run: mvn --batch-mode clean test
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
      - name: SonarCloud Scan
        run: mvn org.sonarsource.scanner.maven:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}